import './globals.scss'
import { Inter } from 'next/font/google'
import Header from "@/components/common/header";
import Client from "@/client";
import Footer from "@/components/common/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }) =>  {

  const { body: data } = await new Client().getById('9971b508-d941-4c59-b34d-2f6e4abf75d8');

  return (
    <html lang="en">
    <head>
      <title>Test Next.js</title>
      <meta name="robots" content="noindex nofollow" />
    </head>
    <body className={inter.className}>
      <Header
        categories={data?.categoryContainer?.categories}
        internalCategories={data?.internalCategoryContainer?.categories}
        mode='external'
        globalVariables={data?.globalVariables}
        types={data?.categoryContainer?.types}
        assetTypes={data?.internalCategoryContainer?.types}
        licenceTypes={data?.categoryContainer?.licenceTypes}
      />
      <main style={{ marginTop: 60 }}>
        {children}
      </main>
    <Footer
      categories={data?.categoryContainer?.categories}
      internalCategories={data?.internalCategoryContainer?.categories}
      mode='external'
      globalVariables={data?.globalVariables}
      types={data?.categoryContainer?.types}
      assetTypes={data?.internalCategoryContainer?.types}
      licenceTypes={data?.categoryContainer?.licenceTypes}
    />
    </body>
    </html>
  )
}

export default RootLayout;
